Flowmon/Flowmon/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
#Use static() to add url mapping to serve static files during development (only)
from django.conf.urls.static import static

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns = [
    path('', RedirectView.as_view(url='accounts/login', permanent=True)),
]

urlpatterns += [
    path('admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application and authentication system
urlpatterns += [
    path('excels/', include(('excels.urls', 'excels'), namespace='excels')), 
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Flowmon/excels/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.import_data, name='index'),
    
]

Flowmon/excels/models.py
from django.db import models
from django.urls import reverse 
# Create your models here.
class Genre(models.Model):
    """Model representing a genre """
    name = models.CharField(
        max_length=200,
        help_text="Enter a genre "
        )

    def __str__(self):

        return self.name


class so_unit(models.Model):
    user = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    types = models.ManyToManyField(Genre, help_text="what is this SO unit type ?")

Flowmon/excels/views.py
from django.shortcuts import render

# Create your views here.
from excels.models import so_unit, Genre
from django.views import generic
from django.http import JsonResponse
import openpyxl
import os
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
import csv


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_user = so_unit.objects.all().count()
    context = {
        'num_user': num_user,
    }
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

# This function allows to read and display uploaded excel files by customers
# def import_data(request):
#     if "GET" == request.method:
#         return render(request, 'index.html', {})
#     else:
#         excel_file = request.FILES["excel_file"]
#         # where to check extension or file size
#         if(excel_file.size < 10485760):
       
#             wb = openpyxl.load_workbook(excel_file)

#             # getting a particular sheet by name out of many sheets
#             worksheet = wb["Sheet1"]
#             print(worksheet)
#             idx = 0
#             excel_data = { }
#             # iterating over the rows and getting value from each cell in row
#             for row in worksheet.iter_rows():
#                 row_data = list()
#                 for cell in row:
#                     row_data.append(str(cell.value))
#                 # excel_data.append(row_data)
#                 excel_data.update({idx:row_data})
#                 idx += 1
#             return JsonResponse(excel_data, safe = False)
#         else:
#             raise ValidationError("The maximum file size that can be uploaded is 10MB")
#             # return render(request, 'index.html', {"excel_data":excel_data})


# --- Export Json Files ---
def import_data(request):
    if "GET" == request.method:
        return render(request, 'index.html', {})
    else:
        excel_file = request.FILES["excel_file"]
        
        fs = FileSystemStorage()
        # save file to local filesystem. 
        # https://docs.djangoproject.com/en/2.2/ref/files/storage/
        excel_file = fs.save(excel_file.name, excel_file)
        
        
        statinfo = os.stat(excel_file)
        file_size = statinfo.st_size
        
        if(file_size < 5000000):
            uploaded_file_url = fs.url(excel_file)
            # fields = []
            # rows = []
            excel_data = { }
            idx = 0 
            # reading csv file
            with open(uploaded_file_url, 'r') as csvfile:
                # create a csv reader object
                csvreader = csv.reader(csvfile, delimiter = ",")
                # extracting field name through first row
                # fields = csvreader.next()
                # extracting each data row one by one and covert list to dictionary type
                for row in csvreader:
                    # rows.append(row)
                    excel_data.update({idx:row})
                    idx += 1
                '''
                 delete local filesystem or fs.save() will create a copy of uploaded file
                 if uploaded file is not unique. (reupload)
                '''
                fs.delete(excel_file)
            return JsonResponse(excel_data, safe = False)
            
        else:
            fs.delete(excel_file)
            raise ValidationError("The maximum file size that can be uploaded is 5MB")
    

        

Flowmon/excels/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
         
         
         
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

Flowmon/excels/templates/index.html
<html>
  <head>
      <title>
        Excel file upload and processing: 
      </title>
    </head>
    <body stype = "margin-top: 30px; margin_left: 30px;">
      <form action="{% url "excels:index" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type = "file"
              title = "Upload excel file"
              name = "excel_file"
              style = "border: 1px solid black; padding: 5 px;"
              required = "required">
        <p>
        <input type="submit"
                value="Upload"
                style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
      </form>

      <p></p>
      <hr>

      {% for row in excel_data %}
        {% for cell in row %}
            {{ cell }}&nbsp;&nbsp;
        {% endfor %}
        <br>
      {% endfor %}
    </body>
  </html>